### ISSUE TITLE
How to get transaction history with token mint address?

### ISSUE THREAD

**Issue by winer328** [dexscreener/google-sheets#4]
Hi, I want to get transaction history with token mint address with dexscreener api.
So i want get data like:
1. first Purchase date/time
2. address of the wallet that bought 
3. Buy Sol (total amount bought in Sol) 
4. Number of purchase transactions 
5. Sell Sol (total amount sold in Sol). 
6. Number of sell transactions

I can get these data with other RPCs but it gets too long time.
I think dexscreener will get shorter time.
How can I get these data with one time?
Thanks.

**Comment by alexandrebini** [comment]
There's no API for historical data.

**Comment by winer328** [comment]
Thanks for your reply even though the reply is too too too slow.
